const Anthropic = require('@anthropic-ai/sdk');
const { Octokit } = require('@octokit/rest');
const fs = require('fs');

// ─── Config from GitHub Actions environment ───────────────────────────────────
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const GITHUB_TOKEN      = process.env.GITHUB_TOKEN;
const REPO_OWNER        = process.env.REPO_OWNER;
const REPO_NAME         = process.env.REPO_NAME;
const ISSUE_NUMBER      = process.env.ISSUE_NUMBER;
const ISSUE_TITLE       = process.env.ISSUE_TITLE;
const ISSUE_BODY        = process.env.ISSUE_BODY;

// ─── Which files Claude can see and modify ────────────────────────────────────
// For UI changes → modify index.html
// For API/backend changes → modify server.js
// Agent will decide based on the issue
const FILES = {
  'public/index.html': fs.readFileSync('./public/index.html', 'utf8'),
  'src/server.js':     fs.readFileSync('./src/server.js', 'utf8')
};

const anthropic = new Anthropic({ apiKey: ANTHROPIC_API_KEY });
const octokit   = new Octokit({ auth: GITHUB_TOKEN });

async function run() {
  console.log(`[AGENT] Starting for Issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}`);

  // ── Step 1: Call Claude with both files ────────────────────────────────────
  console.log('[AGENT] Calling Claude API...');

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 4096,
    messages: [
      {
        role: 'user',
        content: `You are a developer working on a Todo web application.

GitHub Issue Title: ${ISSUE_TITLE}
GitHub Issue Description: ${ISSUE_BODY || 'No description provided.'}

Here are the current files:

--- FILE: public/index.html ---
${FILES['public/index.html']}

--- FILE: src/server.js ---
${FILES['src/server.js']}

Instructions:
- Analyze the issue and decide which file(s) need to change
- Make ONLY the changes needed to fulfill the issue
- Return your response in this EXACT format (no extra text):

FILE: public/index.html
<complete updated content of index.html, or write UNCHANGED if no change needed>

FILE: src/server.js
<complete updated content of server.js, or write UNCHANGED if no change needed>`
      }
    ]
  });

  const rawResponse = response.content[0].text.trim();
  console.log('[AGENT] Claude responded');

  // ── Step 2: Parse Claude's response ───────────────────────────────────────
  const filesToUpdate = {};

  const htmlMatch = rawResponse.match(/FILE: public\/index\.html\n([\s\S]*?)(?=FILE: src\/server\.js|$)/);
  const serverMatch = rawResponse.match(/FILE: src\/server\.js\n([\s\S]*?)$/);

  if (htmlMatch && htmlMatch[1].trim() !== 'UNCHANGED') {
    filesToUpdate['public/index.html'] = htmlMatch[1].trim();
  }
  if (serverMatch && serverMatch[1].trim() !== 'UNCHANGED') {
    filesToUpdate['src/server.js'] = serverMatch[1].trim();
  }

  if (Object.keys(filesToUpdate).length === 0) {
    console.log('[AGENT] No changes needed per Claude');
    return;
  }

  console.log(`[AGENT] Files to update: ${Object.keys(filesToUpdate).join(', ')}`);

  // ── Step 3: Get main branch SHA ────────────────────────────────────────────
  const { data: refData } = await octokit.git.getRef({
    owner: REPO_OWNER,
    repo:  REPO_NAME,
    ref:   'heads/main'
  });
  const mainSHA = refData.object.sha;

  // ── Step 4: Create new branch ──────────────────────────────────────────────
  const branchName = `fix/issue-${ISSUE_NUMBER}-agent`;
  console.log(`[AGENT] Creating branch: ${branchName}`);
  await octokit.git.createRef({
    owner: REPO_OWNER,
    repo:  REPO_NAME,
    ref:   `refs/heads/${branchName}`,
    sha:   mainSHA
  });

  // ── Step 5: Commit each changed file ──────────────────────────────────────
  for (const [filePath, newContent] of Object.entries(filesToUpdate)) {
    const { data: fileData } = await octokit.repos.getContent({
      owner: REPO_OWNER,
      repo:  REPO_NAME,
      path:  filePath,
      ref:   'main'
    });

    await octokit.repos.createOrUpdateFileContents({
      owner:   REPO_OWNER,
      repo:    REPO_NAME,
      path:    filePath,
      message: `fix: AI agent resolves #${ISSUE_NUMBER} — ${ISSUE_TITLE}`,
      content: Buffer.from(newContent).toString('base64'),
      sha:     fileData.sha,
      branch:  branchName
    });

    console.log(`[AGENT] Committed: ${filePath}`);
  }

  // ── Step 6: Open Pull Request ──────────────────────────────────────────────
  const { data: pr } = await octokit.pulls.create({
    owner: REPO_OWNER,
    repo:  REPO_NAME,
    title: `fix: resolves #${ISSUE_NUMBER} — ${ISSUE_TITLE}`,
    head:  branchName,
    base:  'main',
    body: `## AI Agent Generated PR

**Resolves:** #${ISSUE_NUMBER}
**Issue:** ${ISSUE_TITLE}
**Files changed:** ${Object.keys(filesToUpdate).join(', ')}

---
> ⚠️ Auto-generated by Claude AI. Please review before merging.`
  });

  console.log(`[AGENT] ✅ PR raised: ${pr.html_url}`);
}

run().catch(err => {
  console.error('[AGENT] ❌ Error:', err.message);
  process.exit(1);
});
